# Generated by Django 3.0.3 on 2020-02-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstvis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
