# Generated by Django 3.0.3 on 2020-02-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstvis', '0002_user_has_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=128)),
                ('news_theme', models.CharField(default=' ', max_length=128)),
                ('news_content', models.CharField(default=' ', max_length=512)),
                ('news_drug', models.CharField(default=' ', max_length=64)),
                ('news_province', models.CharField(default=' ', max_length=64)),
                ('news_city', models.CharField(default=' ', max_length=64)),
                ('news_county', models.CharField(default=' ', max_length=64)),
                ('news_url', models.CharField(max_length=128)),
                ('news_date', models.DateField(max_length=64)),
            ],
            options={
                'verbose_name': '涉毒新闻表',
                'verbose_name_plural': '涉毒新闻表',
                'ordering': ['-news_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-c_time'], 'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
    ]
