# Generated by Django 3.0.3 on 2020-02-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstvis', '0003_auto_20200216_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_action',
            field=models.CharField(default=' ', max_length=64),
        ),
    ]
